fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "inifile": "https://github.com/puppetlabs/puppetlabs-inifile"
    "apt": "https://github.com/puppetlabs/puppetlabs-apt"
  symlinks:
    "confluent": "#{source_dir}"